AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  languageAnalyze:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: languageAnalyze/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Environment: 
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: ./auth.json
